# file: .github/workflows/manage-project.yml
name: manage-project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: npm install
      # сетап проекта
      - run: make setup
      # запуск тестов
      - run: make test
      # запуск линтера
      - run: make lint
